services:
  we-mp-rss:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: we-mp-rss
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB=sqlite:///./data/db.db
      - USERNAME=admin
      - PASSWORD=admin@123
    volumes:
      - ../data:/app/data
